import React, { useEffect, useState } from 'react';
import { BackHandler, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors, FieldCard, PrimaryButton, Screen, SecondaryButton, StatusChip } from '@crowntrack/ui';
import type { CrewDevelopmentModel } from './useCrewDevelopment';
import type { TabKey } from '../screens';

const Action = ({ label, onPress, disabled, reason }: { label: string; onPress: () => void; disabled?: boolean; reason?: string }) => <View style={styles.action}><SecondaryButton onPress={onPress} disabled={disabled}>{label}</SecondaryButton>{disabled && reason ? <Text style={styles.reason}>{reason}</Text> : null}</View>;
const Confirmation = ({ title, copy, confirm, cancel, confirmLabel }: { title: string; copy: string; confirm: () => void; cancel: () => void; confirmLabel: string }) => <View style={styles.confirmation}><Text style={styles.confirmTitle}>{title}</Text><Text style={styles.body}>{copy}</Text><PrimaryButton onPress={confirm}>{confirmLabel}</PrimaryButton><SecondaryButton onPress={cancel}>Cancel</SecondaryButton></View>;

export const CrewDevelopmentScreen = ({ crew }: { onTab: (tab: TabKey) => void; crew: CrewDevelopmentModel }) => {
  const [confirmReset, setConfirmReset] = useState(false);
  const [confirmRevoke, setConfirmRevoke] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState(false);
  const [manualOpen, setManualOpen] = useState(false);
  const [manualInvitation, setManualInvitation] = useState('');
  const clearTransient = () => { setConfirmReset(false); setConfirmRevoke(false); setConfirmDelete(false); setManualOpen(false); setManualInvitation(''); crew.cancelPairing(); };
  useEffect(() => { const subscription = BackHandler.addEventListener('hardwareBackPress', () => { if (confirmReset || confirmRevoke || confirmDelete || manualOpen || crew.pendingPairing) { clearTransient(); return true; } return false; }); return () => subscription.remove(); }, [confirmReset, confirmRevoke, confirmDelete, manualOpen, crew.pendingPairing]);
  const view = crew.presentation; const gates = view?.actionGates;
  return <Screen><ScrollView contentContainerStyle={styles.scroll} accessibilityLiveRegion="polite" keyboardShouldPersistTaps="handled">
    <Text style={styles.title}>Signed CrewLink</Text>
    <Text style={styles.notice}>Signed messages prove origin and integrity. Location content is not encrypted in this stage.</Text>
    <Text style={styles.body}>Pairing and trust do not authorize group membership. In-process development rider — not a physical phone. Cloud, nearby, and mesh are simulated transports. Connected does not mean a position is current. Delivery is not guaranteed. CrewLink is not emergency or satellite communication.</Text>
    <FieldCard><Text style={styles.heading}>Device identity</Text><StatusChip label={crew.identityState.status.replaceAll('_', ' ').toUpperCase()} tone={crew.identityState.status === 'ready' ? 'ready' : 'unknown'} />{view ? <Text style={styles.body}>Short fingerprint: {view.localFingerprint}</Text> : null}{crew.identityState.status === 'not_created' ? <PrimaryButton onPress={crew.createIdentity}>Create identity</PrimaryButton> : null}{crew.identityState.status === 'ready' ? (confirmReset ? <Confirmation title="Reset device identity?" copy="This stops the signed runtime and clears this device’s identity, private-key storage, pairing invitations, trusted peers, groups, memberships, tombstones, policies, queued updates, locations, ACKs, observations, and rejections." confirm={() => { crew.resetIdentity(); clearTransient(); }} cancel={clearTransient} confirmLabel="Confirm identity reset" /> : <SecondaryButton onPress={() => setConfirmReset(true)}>Reset identity</SecondaryButton>) : null}{crew.identityState.status !== 'ready' && crew.identityState.status !== 'not_created' ? <Text style={styles.warning}>Recovery/reset required. No identity or private key will be silently regenerated.</Text> : null}</FieldCard>
    <FieldCard><Text style={styles.heading}>Trust and membership</Text><Text style={styles.body}>Group: {view?.group?.exists ? `${view.group.origin} · epoch ${view.group.epoch} · ${view.group.owner ? 'owner' : 'member'}` : 'not created'}{`\n`}Pairing: {view?.localPairingConfirmed ? 'confirmed' : 'not confirmed'} · reciprocal development trust: {view?.reciprocalTrust ? 'confirmed' : 'not confirmed'}{`\n`}Development rider: {view?.membership ?? 'unauthorized'}{view?.tombstonePresent ? ' · terminal Stage 3B tombstone' : ''}</Text>{crew.pendingPairing ? <View style={styles.pairing}><Text style={styles.body}>Verification succeeded. Matching this code does not create trust or membership.</Text><Text selectable style={styles.code}>{crew.pendingPairing.code}</Text><PrimaryButton onPress={() => { crew.confirmPairing(); setManualInvitation(''); }}>Confirm pairing code</PrimaryButton><SecondaryButton onPress={clearTransient}>Cancel pairing</SecondaryButton></View> : <><Action label="Stage deterministic development-rider invitation" onPress={crew.stageDevelopmentPairing} /><SecondaryButton onPress={() => setManualOpen(!manualOpen)}>{manualOpen ? 'Hide manual invitation tool' : 'Manual invitation import (development)'}</SecondaryButton>{manualOpen ? <View style={styles.manual}><Text style={styles.body}>Concealed development tool. The raw invitation is cleared after stage, cancel, error, Back, reset, or deletion.</Text><TextInput secureTextEntry value={manualInvitation} onChangeText={setManualInvitation} placeholder="Paste invitation" placeholderTextColor={colors.textTertiary} style={styles.input} accessibilityLabel="Manual pairing invitation" /><PrimaryButton onPress={() => { crew.stageManualPairing(manualInvitation); setManualInvitation(''); setManualOpen(false); }}>Stage manual invitation</PrimaryButton></View> : null}</>}<Action label="Confirm reciprocal development trust" onPress={crew.confirmReciprocalTrust} disabled={crew.identityState.status !== 'ready'} reason="A ready local identity is required." /><Action label="Create verified group" onPress={crew.createGroup} disabled={crew.identityState.status !== 'ready'} reason="A ready local identity is required." /><Action label="Grant group membership" onPress={crew.grantRider} disabled={!gates?.grant.enabled} reason={gates?.grant.reason} /></FieldCard>
    <FieldCard><Text style={styles.heading}>Sharing consent</Text><Text style={styles.body}>Precision: {view?.policy.precision ?? 'reduced'} · retention: {view?.policy.retentionMinutes ?? 0} min{`\n`}Consent: {view?.policy.consentConfirmed ? 'confirmed' : 'not confirmed'} · sharing: {view?.policy.sharingEnabled ? 'enabled' : 'off'}</Text><Action label="Configure reduced precision and 15-minute retention" onPress={crew.configureReduced} /><Action label="Confirm consent" onPress={crew.confirmConsent} /><Action label="Enable sharing" onPress={() => crew.setSharing(true)} disabled={!gates?.sharing.enabled} reason={gates?.sharing.reason} /><Action label="Disable sharing" onPress={() => crew.setSharing(false)} /><Action label="Revoke consent and purge queued updates" onPress={crew.revokeConsent} /></FieldCard>
    <FieldCard><Text style={styles.heading}>Signed delivery</Text><Text style={styles.body}>Local outbound outbox: {view?.outbox.count ?? 0} ({view?.outbox.state ?? 'empty'}) · local ACK: {view?.lastAckOutcome ?? 'none'}{`\n`}Inbound buddy outcome: {view?.lastInboundOutcome ?? 'none'} · duplicate observations: {view?.duplicateObservationCount ?? 0}{`\n`}Cloud: {view?.transports.cloud ?? 'unavailable'} · Nearby: {view?.transports.nearby ?? 'unavailable'} · Mesh: {view?.transports.mesh_radio ?? 'unavailable'}</Text><Action label="Set all transports offline" onPress={crew.offline} /><Action label="Queue local outbound signed update" onPress={crew.queue} disabled={!gates?.queue.enabled} reason={gates?.queue.reason} /><Action label="Connect cloud and flush local outbox" onPress={crew.flushCloud} /><Action label="Deliver signed development-rider inbound update" onPress={crew.deliverBuddy} disabled={!gates?.inbound.enabled} reason={gates?.inbound.reason} /><Action label="Connect nearby and deliver inbound duplicate" onPress={crew.duplicate} disabled={!gates?.duplicate.enabled} reason={gates?.duplicate.reason} /></FieldCard>
    <FieldCard><Text style={styles.heading}>Security scenarios</Text><Text style={styles.body}>Latest rejected category: {view?.lastRejectionCategory ?? 'none'}</Text><Action label="Queue/run forged ACK" onPress={crew.forgedAck} disabled={!gates?.forgedAck.enabled} reason={gates?.forgedAck.reason} /><Action label="Run tampered inbound-location scenario" onPress={crew.tamper} disabled={!gates?.tamper.enabled} reason={gates?.tamper.reason} />{confirmRevoke ? <Confirmation title="Revoke development-rider membership?" copy="This advances the group epoch and creates a terminal Stage 3B tombstone for this exact development-rider identity. It cannot be granted again in this stage; retained position becomes last-known only." confirm={() => { crew.revoke(); clearTransient(); }} cancel={clearTransient} confirmLabel="Confirm revocation" /> : <Action label="Revoke membership" onPress={() => setConfirmRevoke(true)} disabled={!gates?.revoke.enabled} reason={gates?.revoke.reason} />}<Action label="Deliver delayed old-epoch location" onPress={crew.oldEpoch} disabled={!gates?.oldEpoch.enabled} reason={gates?.oldEpoch.reason} /></FieldCard>
    <FieldCard><Text style={styles.heading}>Storage, reload, deletion</Text><Text style={styles.body}>Safe diagnostics: {view ? `${view.diagnostics.groups} groups · ${view.diagnostics.memberships} memberships · ${view.diagnostics.tombstones} tombstones · ${view.diagnostics.acknowledgements} ACKs · ${view.diagnostics.locations} positions` : 'unavailable'}</Text><Action label="Full runtime recreation from local storage" onPress={crew.reload} disabled={!gates?.reload.enabled} reason={gates?.reload.reason} /><Action label="Simulate missing private key" onPress={crew.simulateMissingKey} disabled={crew.identityState.status !== 'ready'} reason="A ready identity is required." /><Action label="Run native cryptography proof" onPress={crew.cryptoProof} disabled={crew.identityState.status !== 'ready'} reason="A ready identity is required." />{confirmDelete ? <Confirmation title="Complete local deletion?" copy="Deletes this device’s identity, private-key storage, pairing invitations, trusted peers, groups, memberships, tombstones, policies, queued updates, locations, ACKs, observations, and rejections. Recipient devices and backups may retain copies already delivered." confirm={() => { crew.deleteAll(); clearTransient(); }} cancel={clearTransient} confirmLabel="Confirm complete local deletion" /> : <Action label="Complete local deletion" onPress={() => setConfirmDelete(true)} disabled={!gates?.delete.enabled} reason={gates?.delete.reason} />}</FieldCard>
    <FieldCard><Text style={styles.heading}>Buddy safety summary</Text><Text style={styles.body}>{view?.summary ?? 'No usable buddy position'}{view?.freshness ? ` · source ${view.freshness.transport}` : ''}</Text><SecondaryButton onPress={() => undefined}>Map buddy details are shown on Map</SecondaryButton></FieldCard>
    <Text style={styles.status}>{crew.lastAction}</Text>
  </ScrollView></Screen>;
};

const styles = StyleSheet.create({ scroll: { gap: 14, paddingBottom: 28 }, title: { color: colors.textPrimary, fontSize: 28, fontWeight: '900' }, heading: { color: colors.textPrimary, fontSize: 18, fontWeight: '900' }, body: { color: colors.textSecondary, lineHeight: 20 }, notice: { color: colors.warning, fontWeight: '900', lineHeight: 21 }, action: { gap: 4 }, reason: { color: colors.textTertiary, fontSize: 12, lineHeight: 17 }, code: { color: colors.textPrimary, fontSize: 28, fontWeight: '900', textAlign: 'center', letterSpacing: 5, paddingVertical: 12 }, status: { color: colors.gps, fontWeight: '700', lineHeight: 20 }, warning: { color: colors.warning, fontWeight: '800', lineHeight: 20 }, pairing: { gap: 10, marginTop: 8 }, manual: { gap: 10, marginTop: 8 }, input: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: 10, color: colors.textPrimary, paddingHorizontal: 12, paddingVertical: 10 }, confirmation: { gap: 10, padding: 12, borderWidth: 1, borderColor: colors.warning, borderRadius: 12, marginTop: 8 }, confirmTitle: { color: colors.textPrimary, fontWeight: '900', fontSize: 16 } });
