import { useCallback, useEffect, useRef, useState } from 'react';
import { cancelNativePairing, confirmNativePairing, createDevelopmentPairingScenario, createNativeIdentity, loadNativeIdentity, resetNativeIdentity, stageNativePairingInvitation, type NativeIdentityState } from './identity';
import { createSignedDevelopmentRuntime, type SignedDevelopmentRuntimeFacade } from './signedDevelopmentRuntime';
import { presentSignedCrew, type SignedCrewPresentation } from './signedCrewPresentation';

export type CrewDevelopmentModel = ReturnType<typeof useCrewDevelopment>;
const safeError = (error: unknown) => error instanceof Error ? error.message.replace(/(?:[A-Za-z0-9_-]{24,})/g, 'redacted') : 'Operation could not complete.';

export const useCrewDevelopment = () => {
  const runtimeRef = useRef<SignedDevelopmentRuntimeFacade>();
  const [identityState, setIdentityState] = useState<NativeIdentityState>({ status: 'not_created', provider: 'Expo SecureStore' });
  const [snapshot, setSnapshot] = useState<Awaited<ReturnType<SignedDevelopmentRuntimeFacade['safeSnapshot']>> | undefined>();
  const [lastAction, setLastAction] = useState('Create a device identity to begin signed CrewLink development.');
  const [pendingPairing, setPendingPairing] = useState<{ invitationId: string; code: string; displayName: string }>();
  const [hydrated, setHydrated] = useState(false);
  const refresh = useCallback(async () => { if (runtimeRef.current) setSnapshot(await runtimeRef.current.safeSnapshot()); }, []);
  const ensureRuntime = useCallback(async () => {
    const identity = await loadNativeIdentity(); setIdentityState(identity);
    if (identity.status !== 'ready') { await runtimeRef.current?.actions.stop(); runtimeRef.current = undefined; return undefined; }
    if (!runtimeRef.current) { runtimeRef.current = await createSignedDevelopmentRuntime(); await runtimeRef.current.actions.start(); }
    await refresh(); return runtimeRef.current;
  }, [refresh]);
  useEffect(() => { void ensureRuntime().catch(e => setLastAction(`Runtime unavailable: ${safeError(e)}`)).finally(() => setHydrated(true)); return () => { void runtimeRef.current?.actions.stop(); runtimeRef.current = undefined; }; }, [ensureRuntime]);
  const run = useCallback((label: string, action: (runtime: SignedDevelopmentRuntimeFacade) => Promise<unknown>) => { void (async () => { const runtime = await ensureRuntime(); if (!runtime) throw new Error('Create a ready device identity first.'); await action(runtime); await refresh(); setLastAction(label); })().catch(e => setLastAction(`${label}: ${safeError(e)}`)); }, [ensureRuntime, refresh]);
  const createIdentity = () => { void createNativeIdentity().then(async state => { setIdentityState(state); await ensureRuntime(); setLastAction('Success: secure device identity created.'); }).catch(e => setLastAction(`Identity creation failed: ${safeError(e)}`)); };
  const resetIdentity = () => { void (async () => { await runtimeRef.current?.actions.deleteHarnessSignedState(); runtimeRef.current = undefined; await resetNativeIdentity(); setIdentityState(await loadNativeIdentity()); setSnapshot(undefined); setPendingPairing(undefined); setLastAction('Success: identity and local CrewLink state reset.'); })().catch(e => setLastAction(`Reset requires retry: ${safeError(e)}`)); };
  const stageDevelopmentPairing = () => { void (async () => { const invitation = await createDevelopmentPairingScenario('valid'); const staged = await stageNativePairingInvitation(invitation); setPendingPairing(staged); setLastAction('Invitation staged. Compare the code, then explicitly confirm pairing.'); })().catch(e => { setPendingPairing(undefined); setLastAction(`Pairing stage failed: ${safeError(e)}`); }); };
  const stageManualPairing = (rawInvitation: string) => { void (async () => { const staged = await stageNativePairingInvitation(JSON.parse(rawInvitation)); setPendingPairing(staged); setLastAction('Invitation staged. Compare the code, then explicitly confirm pairing.'); })().catch(e => { setPendingPairing(undefined); setLastAction(`Manual pairing stage failed: ${safeError(e)}`); }); };
const confirmPairing = () => { if (!pendingPairing) return; void (async () => { await confirmNativePairing(pendingPairing.invitationId); setPendingPairing(undefined); const runtime = await ensureRuntime(); if (!runtime) throw new Error('Ready identity is required to refresh pairing.'); await runtime.actions.refreshConfirmedLocalPairing(); await refresh(); setLastAction('Success: pairing confirmed and local trust refreshed.'); })().catch(e => setLastAction(`Pairing confirmation requires runtime refresh: ${safeError(e)}`)); };
  const cancelPairing = () => { if (!pendingPairing) return; void cancelNativePairing(pendingPairing.invitationId).finally(() => setPendingPairing(undefined)); };
  const deleteAll = () => { void (async () => { await runtimeRef.current?.actions.deleteHarnessSignedState(); runtimeRef.current = undefined; await resetNativeIdentity(); setIdentityState(await loadNativeIdentity()); setSnapshot(undefined); setPendingPairing(undefined); setLastAction('Success: complete local deletion finished. Identity was not recreated.'); })().catch(e => setLastAction(`Deletion requires retry: ${safeError(e)}`)); };
  const recreate = () => { void (async () => { await runtimeRef.current?.actions.stop(); runtimeRef.current = undefined; const runtime = await ensureRuntime(); if (!runtime) throw new Error('Ready identity is required to reconstruct the signed runtime.'); await refresh(); setLastAction('Success: full signed runtime recreation completed.'); })().catch(e => setLastAction(`Runtime reconstruction failed: ${safeError(e)}`)); };
  const simulateMissingKey = () => { void (async () => { const runtime = runtimeRef.current; if (!runtime) throw new Error('Create a ready identity first.'); await runtime.actions.simulateMissingPrivateKey(); runtimeRef.current = undefined; setIdentityState(await loadNativeIdentity()); setSnapshot(undefined); setPendingPairing(undefined); setLastAction('Recovery required: private key removed for the development simulation. No replacement was generated.'); })().catch(e => setLastAction(`Missing-key simulation failed: ${safeError(e)}`)); };
  const cryptoProof = () => { void (async () => { const runtime = await ensureRuntime(); if (!runtime) throw new Error('Create a ready identity first.'); const passed = await runtime.actions.proofNativeCrypto(); setLastAction(passed ? 'Success: native cryptography proof passed.' : 'Crypto proof did not pass.'); })().catch(e => setLastAction(`Crypto proof failed: ${safeError(e)}`)); };
  const presentation: SignedCrewPresentation | undefined = snapshot && presentSignedCrew(snapshot);
  return { hydrated, identityState, snapshot, presentation, lastAction, pendingPairing, createIdentity, resetIdentity, stageDevelopmentPairing, stageManualPairing, confirmPairing, cancelPairing, createGroup: () => run('Success: verified group created.', r => r.actions.createLocalGroup()), confirmReciprocalTrust: () => run('Success: reciprocal development trust confirmed.', r => r.actions.confirmReciprocalDevelopmentTrust()), grantRider: () => run('Success: development rider granted signed membership.', r => r.actions.grantDevelopmentRider()), configureReduced: () => run('Success: reduced precision and retention configured.', r => r.actions.configurePolicy('reduced', 15)), confirmConsent: () => run('Success: consent confirmed.', r => r.actions.confirmConsent(true)), revokeConsent: () => run('Success: consent revoked and unauthorized queued updates purged.', r => r.actions.confirmConsent(false)), setSharing: (enabled: boolean) => run(enabled ? 'Success: sharing enabled.' : 'Success: sharing disabled and unauthorized queued updates purged.', r => r.actions.setSharing(enabled)), offline: () => run('Success: all simulated transports are offline.', r => r.actions.setAllTransportsOffline()), queue: () => run('Success: local outbound signed update queued.', r => r.actions.queueDevelopmentLocation()), flushCloud: () => run('Success: local cloud flush completed.', r => r.actions.setTransportAvailable('cloud', true).then(() => r.actions.flushCloud())), deliverBuddy: () => run('Success: signed development-rider inbound update accepted locally.', r => r.actions.deliverDevelopmentRiderLocation()), duplicate: () => run('Success: nearby inbound duplicate scenario completed.', r => r.actions.setTransportAvailable('nearby', true).then(() => r.actions.duplicateViaNearby())), forgedAck: () => run('Rejected: forged ACK scenario completed.', r => r.actions.injectForgedAck()), tamper: () => run('Rejected: tampered inbound scenario completed.', r => r.actions.injectTamperedLocation()), revoke: () => run('Success: membership revoked with terminal tombstone.', r => r.actions.revokeDevelopmentRider()), oldEpoch: () => run('Rejected: delayed old-epoch scenario completed.', r => r.actions.deliverDelayedOldEpochLocation()), reload: recreate, simulateMissingKey, cryptoProof, deleteAll };
};
