import assert from 'node:assert/strict';
import test from 'node:test';
import { presentSignedCrew } from '../apps/mobile/src/crew/signedCrewPresentation';
import type { SignedDevelopmentSafeSnapshot } from '@crowntrack/crewlink';

const base = (): SignedDevelopmentSafeSnapshot => ({ identityReady: true, localFingerprint: 'abc', group: { exists: true, origin: 'local_owned', epoch: 2, owner: true }, localPairingConfirmed: false, reciprocalTrust: false, remoteMembership: 'unauthorized', tombstonePresent: false, policy: { precision: 'reduced', retentionMinutes: 15, consentConfirmed: false, sharingEnabled: false }, transportStates: { cloud: 'unavailable', nearby: 'unavailable', mesh_radio: 'unavailable' }, outbox: { count: 0, state: 'empty' }, lastAckOutcome: 'none', lastInboundOutcome: 'none', duplicateObservationCount: 0, lastRejectionCategory: 'none', diagnostics: { groups: 1, memberships: 1, tombstones: 0, acknowledgements: 0, locations: 0 }, capabilities: { canDeliverDuplicate: false, canRunForgedAck: false, canRunTamper: false, canRevoke: false, canDeliverOldEpoch: false, canReconstruct: true, canDeleteSignedState: true } });
test('presentation requires pairing and reciprocal trust before grant', () => { const view = presentSignedCrew(base()); assert.equal(view.actionGates.grant.enabled, false); assert.match(view.actionGates.grant.reason ?? '', /pairing/); });
test('presentation gates queue on active membership consent and sharing', () => { const snapshot = base(); snapshot.remoteMembership = 'active'; snapshot.policy.consentConfirmed = true; snapshot.policy.sharingEnabled = true; assert.equal(presentSignedCrew(snapshot).actionGates.queue.enabled, true); });
test('presentation labels revoked positions as last known and never live', () => { const snapshot = base(); snapshot.remoteMembership = 'revoked'; snapshot.tombstonePresent = true; snapshot.latestLocation = { exists: true, ageMs: 0, freshness: 'stale', transport: 'cloud', lastKnownRevoked: true }; assert.equal(presentSignedCrew(snapshot).summary, 'LAST KNOWN — REVOKED'); });
test('presentation contains no raw location or protocol fields', () => { const text = JSON.stringify(presentSignedCrew(base())).toLowerCase(); for (const key of ['latitude', 'longitude', 'signature', 'envelope', 'publickey']) assert.equal(text.includes(key), false); });
test('presentation carries safe diagnostics, inbound outcome, transport states, and gates', () => { const snapshot = base(); snapshot.remoteMembership = 'active'; snapshot.policy.consentConfirmed = true; snapshot.policy.sharingEnabled = true; snapshot.lastInboundOutcome = 'accepted'; snapshot.transportStates.cloud = 'connected'; const view = presentSignedCrew(snapshot); assert.equal(view.transports.cloud, 'connected'); assert.equal(view.lastInboundOutcome, 'accepted'); assert.equal(view.diagnostics.groups, 1); assert.equal(view.actionGates.inbound.enabled, true); assert.equal(view.actionGates.reload.enabled, true); });
